import type { ItemRecord } from './types';

const AREA_MAP: [RegExp, string][] = [
  [/castle morne/i, "Weeping Peninsula"],
  [/weeping peninsula/i, "Weeping Peninsula"],
  [/tombsward/i, "Weeping Peninsula"],
  [/impaler.s catacombs/i, "Weeping Peninsula"],
  [/fourth church of marika/i, "Weeping Peninsula"],
  [/stormveil/i, "Limgrave"],
  [/stormhill/i, "Limgrave"],
  [/limgrave/i, "Limgrave"],
  [/groveside/i, "Limgrave"],
  [/murkwater/i, "Limgrave"],
  [/summonwater/i, "Limgrave"],
  [/fringefolk/i, "Limgrave"],
  [/stranded graveyard/i, "Limgrave"],
  [/warmaster.s shack/i, "Limgrave"],
  [/gatefront/i, "Limgrave"],
  [/dragon.burnt/i, "Limgrave"],
  [/coastal cave/i, "Limgrave"],
  [/highroad cave/i, "Limgrave"],
  [/church of elleh/i, "Limgrave"],
  [/kale shop/i, "Limgrave"],
  [/knight bernahl shop/i, "Limgrave"],
  [/sorceress sellen/i, "Limgrave"],
  [/bloody finger nerijus/i, "Limgrave"],
  [/chapel of anticipation/i, "Limgrave"],
  [/raya lucaria/i, "Liurnia"],
  [/liurnia/i, "Liurnia"],
  [/caria manor/i, "Liurnia"],
  [/academy gate/i, "Liurnia"],
  [/rose church/i, "Liurnia"],
  [/revenger.s shack/i, "Liurnia"],
  [/converted tower/i, "Liurnia"],
  [/laskyar/i, "Liurnia"],
  [/ruin.strewn/i, "Liurnia"],
  [/albinaurics/i, "Liurnia"],
  [/frenzied flame village/i, "Liurnia"],
  [/church of inhibition/i, "Liurnia"],
  [/bellum/i, "Liurnia"],
  [/church of vows/i, "Liurnia"],
  [/miriel/i, "Liurnia"],
  [/preceptor seluvis/i, "Liurnia"],
  [/seluvis/i, "Liurnia"],
  [/ranni.s questline/i, "Liurnia"],
  [/royal knight loretta/i, "Liurnia"],
  [/thops/i, "Liurnia"],
  [/redmane castle/i, "Caelid"],
  [/caelid/i, "Caelid"],
  [/sellia/i, "Caelid"],
  [/dragonbarrow/i, "Caelid"],
  [/dragonsbarrow/i, "Caelid"],
  [/bestial sanctum/i, "Caelid"],
  [/fort gael/i, "Caelid"],
  [/caelem ruins/i, "Caelid"],
  [/aeonia/i, "Caelid"],
  [/gaol cave/i, "Caelid"],
  [/forsaken ruins/i, "Caelid"],
  [/street of sages ruins/i, "Caelid"],
  [/gowry/i, "Caelid"],
  [/commander o.neil/i, "Caelid"],
  [/gael tunnel/i, "Caelid"],
  [/mt\.? gelmir/i, "Mt. Gelmir"],
  [/gelmir hero.s grave/i, "Mt. Gelmir"],
  [/volcano manor/i, "Mt. Gelmir"],
  [/hermit.s shack/i, "Mt. Gelmir"],
  [/road of iniquity/i, "Mt. Gelmir"],
  [/hermit village/i, "Mt. Gelmir"],
  [/patches shop/i, "Mt. Gelmir"],
  [/bernhahl at volcano manor/i, "Mt. Gelmir"],
  [/bernahl at volcano manor/i, "Mt. Gelmir"],
  [/recusant bernahl/i, "Mt. Gelmir"],
  [/leyndell royal capital/i, "Altus Plateau"],
  [/altus plateau/i, "Altus Plateau"],
  [/auriza/i, "Altus Plateau"],
  [/sainted hero.s grave/i, "Altus Plateau"],
  [/old altus tunnel/i, "Altus Plateau"],
  [/abandoned coffin/i, "Altus Plateau"],
  [/lux ruins/i, "Altus Plateau"],
  [/dominula/i, "Altus Plateau"],
  [/shaded castle/i, "Altus Plateau"],
  [/leyndell.*ashen/i, "Altus Plateau"],
  [/leyndell/i, "Altus Plateau"],
  [/subterranean shunning/i, "Altus Plateau"],
  [/forbidden lands/i, "Altus Plateau"],
  [/elemer of the br/i, "Altus Plateau"],
  [/giant.conquering/i, "Mountaintops of the Giants"],
  [/castle sol/i, "Mountaintops of the Giants"],
  [/mountaintops/i, "Mountaintops of the Giants"],
  [/zamor ruins/i, "Mountaintops of the Giants"],
  [/flame peak/i, "Mountaintops of the Giants"],
  [/consecrated snowfield/i, "Consecrated Snowfield"],
  [/ordina/i, "Consecrated Snowfield"],
  [/inner consecrated/i, "Consecrated Snowfield"],
  [/siofra/i, "Siofra River"],
  [/nokron/i, "Nokron, Eternal City"],
  [/nokstella/i, "Ainsel River"],
  [/ainsel/i, "Ainsel River"],
  [/deeproot/i, "Deeproot Depths"],
  [/lake of rot/i, "Lake of Rot"],
  [/grand cloister/i, "Lake of Rot"],
  [/mohgwyn/i, "Mohgwyn Palace"],
  [/farum azula/i, "Crumbling Farum Azula"],
  [/crumbling farum/i, "Crumbling Farum Azula"],
  [/elphael/i, "Miquella's Haligtree"],
  [/haligtree/i, "Miquella's Haligtree"],
  [/enir.ilim/i, "Shadow of the Erdtree"],
  [/scadu/i, "Shadow of the Erdtree"],
  [/rauh/i, "Shadow of the Erdtree"],
  [/cerulean coast/i, "Shadow of the Erdtree"],
  [/gravesite plain/i, "Shadow of the Erdtree"],
  [/shadow.keep/i, "Shadow of the Erdtree"],
  [/finger ruins/i, "Shadow of the Erdtree"],
  [/jagged peak/i, "Shadow of the Erdtree"],
  [/abyssal woods/i, "Shadow of the Erdtree"],
  [/roundtable hold/i, "Roundtable Hold"],
  [/twin maiden husks?/i, "Roundtable Hold"],
  [/enia shop/i, "Roundtable Hold"],
  [/automatically rec(?:ei|ie)ved/i, "Starting Loadout"],
];

function inferArea(loc: string): string {
  for (const [re, a] of AREA_MAP) { if (re.test(loc)) return a; } return 'Various';
}

let _c = 0;
function r(n: string, l: string, s: ItemRecord['sourceType']): ItemRecord {
  return { id: 'v-' + ++_c, itemName: n, originalItem: null, locationName: l, area: inferArea(l), sourceType: s, isKeyItem: false, rawLine: n + ' — ' + l, section: 'vanilla' };
}

export const VANILLA_ITEMS: ItemRecord[] = [
 r("Dagger", "Twin Maiden Husk Shop, Foot Soldier Drop", 'shop'),
 r("Parrying Dagger", "Patches Shop", 'shop'),
 r("Misericorde", "Stormveil Castle", 'ground_pickup'),
 r("Great Knife", "Craftmans Shack, Demihuman Assassin Drop", 'enemy_drop'),
 r("Bloodstained Dagger", "Demihuman Cheif Drop, Demihuman Assassin Drop", 'enemy_drop'),
 r("Erdsteel Dagger", "Leyndell Royal Capital, Kenneth Haight Questline", 'event'),
 r("Wakizashi", "Gaol Cave", 'ground_pickup'),
 r("Celebrant's Sickle", "Celebrants Drop", 'enemy_drop'),
 r("Ivory Sickle", "Village of the Albinaurics", 'ground_pickup'),
 r("Crystal Knife", "Raya Lucaria Crystal Tunnel", 'ground_pickup'),
 r("Scorpion's Stinger", "Grand Cloister", 'ground_pickup'),
 r("Cinquedea", "Bestial Sanctum Exterior", 'ground_pickup'),
 r("Glintstone Kris", "Sorceress Sellen Questline", 'event'),
 r("Reduvia", "Bloody Finger Nerijus Drop", 'boss_drop'),
 r("Blade of Calling", "Elevator to Forbidden Lands", 'ground_pickup'),
 r("Black Knife", "Sainted Hero's Grave", 'boss_drop'),
 r("Short Sword", "Nomadic Merchant Shop (North Limgrave), Highwayman Drop", 'shop'),
 r("Longsword", "Twin Maiden Husk Shop", 'shop'),
 r("Broadsword", "Nomadic Merchant Shop (West Limgrave)", 'shop'),
 r("Weathered Straight Sword", "Commoner Drop", 'enemy_drop'),
 r("Lordsworn's Straight Sword", "Soldier Drop", 'enemy_drop'),
 r("Noble's Slender Sword", "Wandering Noble Drop", 'enemy_drop'),
 r("Cane Sword", "Leyndell Royal Capital", 'ground_pickup'),
 r("Warhawk's Talon", "Warhawk Drop", 'enemy_drop'),
 r("Lazuli Glintstone Sword", "Lazuli Sorcerer Drop", 'enemy_drop'),
 r("Carian Knight's Sword", "Liurnia of the Lakes Wagon", 'ground_pickup'),
 r("Crystal Sword", "Village of the Albinaurics", 'ground_pickup'),
 r("Rotten Crystal Sword", "Elphael, Brace of the Haligtree", 'ground_pickup'),
 r("Miquellan Knight's Sword", "Elphael, Brace of the Haligtree", 'ground_pickup'),
 r("Ornamental Straight Sword", "Grafted Scion (Chapel of Anticipation)", 'boss_drop'),
 r("Golden Epitaph", "Auriza Hero's Grave", 'ground_pickup'),
 r("Sword of St. Trina", "Forsaken Ruins", 'ground_pickup'),
 r("Regalia of Eochaid", "Gaol Cave", 'ground_pickup'),
 r("Coded Sword", "Leyndell Royal Capital", 'ground_pickup'),
 r("Sword of Night and Flame", "Caria Manor", 'ground_pickup'),
 r("Bastard Sword", "Nomadic Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Claymore", "Castle Morne", 'ground_pickup'),
 r("Iron Greatsword", "Lesser Leonine Misbegotten Drop", 'enemy_drop'),
 r("Lordsworn's Greatsword", "Gatefront Ruins Wagon", 'ground_pickup'),
 r("Knight's Greatsword", "Knight Drop", 'enemy_drop'),
 r("Banished Knight's Greatsword", "Banished Knight Drop", 'enemy_drop'),
 r("Forked Greatsword", "Elder Imp Drop", 'enemy_drop'),
 r("Flamberge", "Redmane Castle", 'ground_pickup'),
 r("Gargoyle's Greatsword", "Valiant Gargoyle Duo Drop", 'boss_drop'),
 r("Gargoyle's Blackblade", "Caelid", 'boss_drop'),
 r("Inseparable Sword", "Prince of Death's Throne (D's Questline)", 'event'),
 r("Sword of Milos", "Dung Eater's Questline", 'event'),
 r("Marais Executioner's Sword", "Elemer of the Brair Drop", 'boss_drop'),
 r("Ordovis's Greatsword", "Crucible Knight Ordovis Drop", 'boss_drop'),
 r("Alabaster Lord's Sword", "Alabaster Lord Drop", 'enemy_drop'),
 r("Death's Poker", "Caelid", 'boss_drop'),
 r("Helphen's Steeple", "Tibia Mariner (Mountaintops)", 'boss_drop'),
 r("Blasphemous Blade", "Remembrance of the Blasphemous option", 'boss_drop'),
 r("Golden Order Greatsword", "Misbegotten Crusader Drop", 'boss_drop'),
 r("Dark Moon Greatsword", "Ranni's Questline", 'event'),
 r("Sacred Relic Sword", "Elden Remembrance option", 'boss_drop'),
 r("Zweihander", "Isolated Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Greatsword", "Caelid Wagon", 'ground_pickup'),
 r("Watchdog's Greatsword", "Sword Wielding", 'enemy_drop'),
 r("Troll's Golden Sword", "Altus Plateau Wagon", 'ground_pickup'),
 r("Troll Knight's Sword", "Caria Manor", 'enemy_drop'),
 r("Royal Greatsword", "Ranni's Questline", 'event'),
 r("Grafted Blade Greatsword", "Leonine Misbegotten Drop", 'boss_drop'),
 r("Ruins Greatsword", "Redmane Castle", 'boss_drop'),
 r("Starscourge Greatsword", "Remembrance of the Starscourge option", 'boss_drop'),
 r("Godslayer's Greatsword", "Divine Tower of Caelid", 'ground_pickup'),
 r("Maliketh's Black Blade", "Remembrance of the Black Blade option", 'boss_drop'),
 r("Uchigatana", "Deathtouched Catacombs", 'ground_pickup'),
 r("Nagakiba", "Yura's Questline", 'event'),
 r("Serpentbone Blade", "Second Volcano Manor Assignment Reward", 'event'),
 r("Meteoric Ore Blade", "Caelid Waypoint Ruins", 'ground_pickup'),
 r("Moonveil", "Gael Tunnel", 'boss_drop'),
 r("Rivers of Blood", "Bloody Finger Okina Drop", 'boss_drop'),
 r("Dragonscale Blade", "Lake of Rot", 'boss_drop'),
 r("Hand of Malenia", "Remembrance of the Rot Goddess option", 'boss_drop'),
 r("Scimitar", "Twin Maiden Husk Shop", 'shop'),
 r("Falchion", "Sword Wielding", 'enemy_drop'),
 r("Shamshir", "Highroad Cave", 'ground_pickup'),
 r("Grossmesser", "Sword Wielding", 'enemy_drop'),
 r("Bandit's Curved Sword", "Skeleton Assassin Drop", 'enemy_drop'),
 r("Shotel", "Nomadic Merchant Shop (Siofra River)", 'shop'),
 r("Scavenger's Curved Sword", "Mt. Gelmir", 'ground_pickup'),
 r("Mantis Blade", "Gelmir Hero's Grave", 'boss_drop'),
 r("Beastman's Curved Sword", "Azula Beastman Drop", 'enemy_drop'),
 r("Flowing Curved Sword", "Consecrated Snowfield Wagon", 'ground_pickup'),
 r("Serpent-God's Curved Sword", "Ruin-Strewn Precipice", 'ground_pickup'),
 r("Magma Blade", "Sword Wielding", 'enemy_drop'),
 r("Nox Flowing Sword", "Nox Swordstress & Nox Priest Drop", 'boss_drop'),
 r("Wing of Astel", "Uhl Palace Ruins", 'ground_pickup'),
 r("Eclipse Shotel", "Castle Sol", 'ground_pickup'),
 r("Dismounter", "Kaiden Sellsword Drop", 'enemy_drop'),
 r("Omen Cleaver", "Omen Drop", 'enemy_drop'),
 r("Monk's Flameblade", "Firemonk Drop", 'enemy_drop'),
 r("Beastman's Cleaver", "Azula Beastman Drop", 'enemy_drop'),
 r("Bloodhound's Fang", "Bloodhound Knight Darriwil Drop", 'boss_drop'),
 r("Onyx Lord's Greatsword", "Onyx Lord Drop", 'boss_drop'),
 r("Zamor Curved Sword", "Ancient Hero of Zamor (Giant-Conquering Hero's Grave)", 'boss_drop'),
 r("Magma Wyrm's Scalesword", "Magma Wyrm Makar Drop", 'boss_drop'),
 r("Morgott's Cursed Sword", "Remembrance of the Omen King option", 'boss_drop'),
 r("Rapier", "Twin Maiden Husk Shop", 'shop'),
 r("Estoc", "Nomadic Merchant Shop (South Liurnia), Patches Shop (Liurnia)", 'shop'),
 r("Noble's Estoc", "Wandering Noble (Thrusting Sword Wielding)", 'enemy_drop'),
 r("Cleanrot Knight's Sword", "Cleanrot Knight Drop", 'enemy_drop'),
 r("Rogier's Rapier", "Rogier's Questline", 'event'),
 r("Antspur Rapier", "Maleigh Marais, Shaded Castle Castellan Drop", 'boss_drop'),
 r("Frozen Needle", "Kingsrealm Ruins", 'ground_pickup'),
 r("Great Epee", "South Limgrave", 'ground_pickup'),
 r("Godskin Stitcher", "Godskin Noble (Volcano Manor)", 'boss_drop'),
 r("Bloody Helice", "Writheblood Ruins", 'ground_pickup'),
 r("Dragon King's Cragblade", "Remembrance of the Dragonlord option", 'boss_drop'),
 r("Hand Axe", "Nomadic Merchant Shop (East Limgrave)", 'shop'),
 r("Forked Hatchet", "Imp Drop", 'enemy_drop'),
 r("Battle Axe", "Twin Maiden Husk Shop", 'shop'),
 r("Warped Axe", "Fell Omen Drop", 'enemy_drop'),
 r("Jawbone Axe", "Ancestral Follower Drop", 'enemy_drop'),
 r("Iron Cleaver", "Misbegotten Drop", 'enemy_drop'),
 r("Highland Axe", "Stormveil Castle", 'ground_pickup'),
 r("Celebrant's Cleaver", "Celebrant Drop", 'enemy_drop'),
 r("Sacrificial Axe", "Weeping Peninsula", 'boss_drop'),
 r("Icerind Hatchet", "Temple Quarter (Liurnia)", 'ground_pickup'),
 r("Ripple Blade", "Pidia Carian Servant Shop", 'shop'),
 r("Stormhawk Axe", "Leyndell Royal Capital, Castle Sol, Nepheli Loux Drop", 'enemy_drop'),
 r("Rosus' Axe", "Black Knife Catacombs", 'ground_pickup'),
 r("Greataxe", "Limgrave Wagon", 'ground_pickup'),
 r("Cresent Moon Axe", "Axe Wielding", 'enemy_drop'),
 r("Longhaft Axe", "Misbegotten Warrior Drop", 'enemy_drop'),
 r("Executioner's Greataxe", "Skeleton Warrior Drop", 'enemy_drop'),
 r("Great Omenkiller Cleaver", "Perfumer's Grotto", 'boss_drop'),
 r("Rusted Anchor", "Scaly Misbegotten Drop", 'boss_drop'),
 r("Butchering Knife", "Anastasia, Tarnished-Eater Drop", 'boss_drop'),
 r("Gargoyle's Great Axe", "Leyndell Capital Outskirts", 'enemy_drop'),
 r("Gargoyle's Black Axe", "Black Blade Kindred (Mountaintops)", 'boss_drop'),
 r("Winged Greathorn", "Remembrance of the Regal Ancestor option", 'boss_drop'),
 r("Axe of Godrick", "Remembrance of the Grafted option", 'boss_drop'),
 r("Club", "Nomadic Merchant Shop (West Limgrave), Demihuman Drop", 'shop'),
 r("Spiked Club", "Demihuman Drop", 'enemy_drop'),
 r("Stone Club", "Battlemage Drop", 'enemy_drop'),
 r("Mace", "Twin Maiden Husk Shop", 'shop'),
 r("Morning Star", "Weeping Peninsula", 'ground_pickup'),
 r("Warpick", "Soldier Drop", 'enemy_drop'),
 r("Hammer", "Leyndell Royal Capital", 'ground_pickup'),
 r("Monk's Flamemace", "Firemonk Drop", 'enemy_drop'),
 r("Varre's Bouquet", "White-Faced Varre Questline", 'event'),
 r("Envoy's Horn", "Oracle Envoy Drop", 'enemy_drop'),
 r("Nox Flowing Hammer", "Nokron Eternal City", 'ground_pickup'),
 r("Ringed Finger", "Gelmir Hero's Grave", 'ground_pickup'),
 r("Scepter of the All-Knowing", "Sir Gideon Ofnir the All-Knowing Drop", 'boss_drop'),
 r("Marika's Hammer", "Elden Remembrance option", 'boss_drop'),
 r("Large Club", "South Limgrave", 'ground_pickup'),
 r("Great Mace", "South Altus Plateau", 'ground_pickup'),
 r("Pickaxe", "Miner Drop", 'enemy_drop'),
 r("Brick Hammer", "Stormveil Castle", 'ground_pickup'),
 r("Battle Hammer", "Lesser Grave Warden Duelist Drop", 'enemy_drop'),
 r("Rotten Battle Hammer", "Consecrated Snowfields", 'enemy_drop'),
 r("Celebrant's Skull", "Windmill Village", 'ground_pickup'),
 r("Great Stars", "Altus Plateau Wagon", 'ground_pickup'),
 r("Greathorn Hammer", "Ancestral Follower Drop", 'enemy_drop'),
 r("Envoy's Long Horn", "Large Oracle Envoy Drop", 'enemy_drop'),
 r("Cranial Vessel Candlestand", "Giant-Conquering Hero's Grave", 'ground_pickup'),
 r("Beastclaw Greathammer", "7th Deathroot Reward (Gurranq, Beast Clergyman)", 'event'),
 r("Devourer's Scepter", "Bernahl at Volcano Manor", 'boss_drop'),
 r("Duelist Greataxe", "Lesser Grave Warden Duelist Drop", 'enemy_drop'),
 r("Rotten Greataxe", "Consecrated Snowfields", 'enemy_drop'),
 r("Golem's Halberd", "Golem Drop", 'enemy_drop'),
 r("Giant-Crusher", "Leyndell Capital Outskirts", 'ground_pickup'),
 r("Prelate's Inferno Crozier", "Fire Prelate Drop", 'enemy_drop'),
 r("Great Club", "Stonedigger Troll Drop", 'boss_drop'),
 r("Troll's Hammer", "Old Altus Tunnel", 'ground_pickup'),
 r("Dragon Greatclaw", "Leyndell", 'boss_drop'),
 r("Watchdog's Staff", "Road's End Catacombs", 'ground_pickup'),
 r("Rotten Staff", "Miquella's Haligtree", 'enemy_drop'),
 r("Envoy's Greathorn", "Giant Oracle Envoy Drop", 'enemy_drop'),
 r("Ghiza's Wheel", "Inquisitor Ghiza Drop", 'boss_drop'),
 r("Fallingstar Beast Jaw", "Full-Grown Fallingstar Beast Drop", 'boss_drop'),
 r("Axe of Godfrey", "Remembrance of the Grafted option", 'boss_drop'),
 r("Short Spear", "Twin Maiden Husk Shop", 'shop'),
 r("Iron Spear", "Fallen Hawks Soldier Drop", 'enemy_drop'),
 r("Spear", "Exile Drop", 'enemy_drop'),
 r("Partisan", "Knight Drop", 'enemy_drop'),
 r("Pike", "Stormveil Castle", 'ground_pickup'),
 r("Spiked Spear", "Marionette Soldier Drop", 'enemy_drop'),
 r("Cross-Naginata", "Gael Tunnel", 'ground_pickup'),
 r("Clayman's Harpoon", "Clayman Drop", 'enemy_drop'),
 r("Celebrant's Rib-Rake", "Celebrant Drop", 'enemy_drop'),
 r("Torchpole", "Foot Soldier Drop", 'enemy_drop'),
 r("Inquisitor's Girandole", "Abductor Virgins Drop", 'boss_drop'),
 r("Crystal Spear", "Sellia Hideaway", 'ground_pickup'),
 r("Rotten Crystal Spear", "Putrid Crystalian Drop", 'enemy_drop'),
 r("Cleanrot Spear", "Cleanrot Knight Drop", 'enemy_drop'),
 r("Death Ritual Spear", "Mountaintops", 'boss_drop'),
 r("Bolt of Gransax", "Leyndell Royal Capital", 'ground_pickup'),
 r("Lance", "North Limgrave", 'ground_pickup'),
 r("Treespear", "South Liurnia of the Lakes Wagon", 'ground_pickup'),
 r("Serpent-Hunter", "Volcano Manor", 'ground_pickup'),
 r("Siluria's Tree", "Crucible Knight Siluria Drop", 'boss_drop'),
 r("Vyke's War Spear", "Festering Fingerprint Vyke", 'boss_drop'),
 r("Mohgwyn's Sacred Spear", "Remembrance of the Blood Lord option", 'boss_drop'),
 r("Halberd", "Nomadic Merchant Shop (North Limgrave)", 'shop'),
 r("Banished Knight's Halberd", "Banished Knight Drop", 'enemy_drop'),
 r("Lucerne", "Liurnia Highway", 'ground_pickup'),
 r("Glaive", "Skeleton Drop", 'enemy_drop'),
 r("Vulgar Militia Shotel", "Vulgar Militia Drop", 'enemy_drop'),
 r("Vulgar Militia Saw", "Vulgar Militia Drop", 'enemy_drop'),
 r("Gaurdian's Swordspear", "Erdtree Guardian Drop", 'enemy_drop'),
 r("Gargoyle's Halberd", "Leyndell Royal Capital", 'enemy_drop'),
 r("Gargoyle's Black Halberd", "Caelid", 'boss_drop'),
 r("Nightrider Glaive", "North Liurnia of the Lakes", 'boss_drop'),
 r("Pest's Glaive", "Lesser Kindred of Rot Drop", 'enemy_drop'),
 r("Ripple Crescent Halberd", "Albinauric (2nd Gen) Drop", 'enemy_drop'),
 r("Golden Halberd", "Limgrave", 'boss_drop'),
 r("Dragon Halberd", "Siofra River", 'boss_drop'),
 r("Loretta's War Sickle", "Loretta, Knight of the Haligtree Drop", 'boss_drop'),
 r("Commander's Standard", "Commander O'Neil Drop", 'boss_drop'),
 r("Scythe", "Cliffbottom Catacombs", 'ground_pickup'),
 r("Grave Scythe", "Skeleton Mage Drop", 'enemy_drop'),
 r("Halo Scythe", "Cleanrot Knight Drop", 'enemy_drop'),
 r("Winged Scythe", "Tombsward Ruins", 'ground_pickup'),
 r("Twinblade", "Dragon Burnt Ruins", 'ground_pickup'),
 r("Twinned Knight Swords", "East Windmill Pasture", 'ground_pickup'),
 r("Godskin Peeler", "Windmill Village", 'boss_drop'),
 r("Gargoyle's Twinblade", "Valiant Gargoyle Duo Drop", 'boss_drop'),
 r("Gargoyle's Black Blades", "Mountaintops", 'boss_drop'),
 r("Eleonora's Poleblade", "Eleonora, Violet Bloody Finger Drop", 'boss_drop'),
 r("Flail", "Gatefront Ruins Wagon", 'ground_pickup'),
 r("Nightrider Flail", "Weeping Peninsula", 'boss_drop'),
 r("Chainlink Flail", "Pumpkin Head Drop", 'enemy_drop'),
 r("Family Heads", "Necromancer Garris Drop", 'boss_drop'),
 r("Bastard's Stars", "Remembrance of the Naturalborn option", 'boss_drop'),
 r("Caestus", "Gatekeeper Gostoc Shop", 'shop'),
 r("Spiked Caestus", "Isolated Merchant Shop (Dragonsbarrow)", 'shop'),
 r("Katar", "Fort Gael", 'ground_pickup'),
 r("Iron Ball", "Blackguard Big Boggart Drop", 'enemy_drop'),
 r("Star Fist", "Leyndell Royal Capital", 'ground_pickup'),
 r("ClingingBone", "Ensha of the Royal Remains Drop", 'boss_drop'),
 r("Veteran's Prosthesis", "Commander Niall Drop", 'boss_drop'),
 r("Cipher Pata", "Roundtable Hold", 'ground_pickup'),
 r("Grafted Dragon", "Remembrance of the Grafted option", 'boss_drop'),
 r("Hookclaws", "Stormveil Castle", 'ground_pickup'),
 r("Bloodhound Claws", "Volcano Manor", 'enemy_drop'),
 r("Venomous Fang", "Abandoned Cave", 'ground_pickup'),
 r("Raptor Talons", "Sage's Cave", 'ground_pickup'),
 r("Whip", "Castle Morne", 'ground_pickup'),
 r("Thorned Whip", "Fire Prelate Drop", 'enemy_drop'),
 r("Urumi", "Caria Manor", 'ground_pickup'),
 r("Hoslow's Petal Whip", "Juno Hoslow Drop, Daillos Drop", 'boss_drop'),
 r("Magma Whip Candlestick", "Patches Questline", 'event'),
 r("Giant's Red Braid", "Remembrance of the Fire Giant option", 'boss_drop'),
 r("Royal House Scroll", "South Limgrave", 'ground_pickup'),
 r("Academy Scroll", "Lake Facing Cliffs (South Liurnia)", 'ground_pickup'),
 r("Conspectus Scroll", "Great Hall (Raya Lucaria Academy)", 'ground_pickup'),
 r("Brairs of Punishment", "South Mountaintops", 'ground_pickup'),
 r("Brairs of Sin", "East Liurnia", 'ground_pickup'),
 r("Carian Greatsword", "Miriel, Pastor of Vows Shop", 'shop'),
 r("Carian Phalanx", "Preceptor Seluvis Shop", 'shop'),
 r("Carian Piercer", "Scarab Reward (Caria Manor)", 'enemy_drop'),
 r("Carian Retaliation", "Preceptor Seluvis Shop", 'shop'),
 r("Carian Slicer", "Royal House Scroll Unlock (Sorceress Sellen or Miriel)", 'shop'),
 r("Glintblade Phalanx", "Royal House Scroll Unlock (Sorceress Sellen or Miriel)", 'shop'),
 r("Greatblade Phalanx", "Bols, Carian Knight Drop", 'boss_drop'),
 r("Lucidity", "Preceptor Miriam (Inverted) Drop", 'boss_drop'),
 r("Magic Downpour", "Preceptor Miriam Drop", 'boss_drop'),
 r("Magic Glintblade", "Miriel, Pastor of Vows Shop", 'shop'),
 r("Great Oracular Bubble", "Scarab Reward (Siofra River)", 'enemy_drop'),
 r("Oracle Bubbles", "Scarab Reward (Siofra River)", 'enemy_drop'),
 r("Crystal Release", "Academy Crystal Cave", 'boss_drop'),
 r("Crystal Torrent", "Sellia Hideaway", 'boss_drop'),
 r("Shattering Crystal", "Raya Lucaria Academy", 'ground_pickup'),
 r("Ancient Death Rancor", "Liurnia of the Lakes", 'boss_drop'),
 r("Explosive Ghostflame", "Consecrated Snowfields", 'boss_drop'),
 r("Fia's Mist", "Fia's Champions Drop", 'boss_drop'),
 r("Rancorcall", "Scarab Reward (Stormveil Castle Underground)", 'enemy_drop'),
 r("Tibia's Summons", "Altus Plateau", 'boss_drop'),
 r("Ranni's Dark Moon", "Chelona's Rise", 'ground_pickup'),
 r("Rennala's Full Moon", "Remembrance of the Full Moon Queen option", 'boss_drop'),
 r("Cannon of Haima", "Converted Fringe Tower", 'ground_pickup'),
 r("Comet", "Raya Lucaria Academy", 'ground_pickup'),
 r("Crystal Barrage", "Sorceress Sellen Shop", 'shop'),
 r("Crystal Burst", "Weeping Peninsula", 'enemy_drop'),
 r("Gavel of Haima", "Converted Fringe Tower", 'ground_pickup'),
 r("Glintstone Arc", "Scarab Reward (Agheel Lake), Sorceress Sellen Shop", 'shop'),
 r("Glintstone Cometshard", "Conspectus Scroll Unlock (Sorceress Sellen or Miriel)", 'shop'),
 r("Glintstone Pebble", "Sorceress Sellen Shop", 'shop'),
 r("Glintstone Stars", "Sorceress Sellen Shop", 'shop'),
 r("Great Glintstone Shard", "Academy Scroll Unlock (Sorceress Sellen or Miriel)", 'shop'),
 r("Rock Blaster", "Sellia Crystal Tunnel", 'ground_pickup'),
 r("Scholar's Armament", "Sorceress Sellen Shop", 'shop'),
 r("Scholar's Shield", "Sorceress Sellen Shop", 'shop'),
 r("Shard Spiral", "Sorceress Sellen Shop (Questline Progress as Ally)", 'shop'),
 r("Shatter Earth", "Raya Lucaria Crystal Tunnel", 'ground_pickup'),
 r("Star Shower", "Conspectus Scroll Unlock (Sorceress Sellen or Miriel)", 'shop'),
 r("Starlight", "Thops Shop", 'shop'),
 r("Swift Glintstone Shard", "Academy Scroll Unlock (Sorceress Sellen or Miriel)", 'shop'),
 r("Terra Magica", "Academy Crystal Cave", 'ground_pickup'),
 r("Thop's Barrier", "Thops Questline Progress", 'event'),
 r("Collapsing Stars", "War-Dead Catacombs", 'ground_pickup'),
 r("Gravity Well", "Raya Lucaria Academy", 'ground_pickup'),
 r("Meteorite", "Alabaster Lord Drop", 'boss_drop'),
 r("Meteorite of Astel", "Astel, Stars of Darkness Drop", 'boss_drop'),
 r("Rock Sling", "Street of Sages Ruins", 'ground_pickup'),
 r("Loretta's Greatbow", "Royal Knight Loretta Drop", 'boss_drop'),
 r("Loretta's Mastery", "Loretta, Knight of the Haligtree Drop", 'boss_drop'),
 r("Gelmir's Fury", "Bernahl at Volcano Manor", 'event'),
 r("Magma Shot", "Volcano Manor 1st Contract Reward", 'event'),
 r("Roiling Magma", "Hermit's Shack (Mt. Gelmir)", 'ground_pickup'),
 r("Rykard's Rancor", "Remembrance of the Blasphemous option", 'boss_drop'),
 r("Ambush Shard", "Witchbane Ruins", 'ground_pickup'),
 r("Eternal Darkness", "Tower in Caelid (near Church of the Plague)", 'ground_pickup'),
 r("Night Comet", "Sellia, Town of Sorcery", 'ground_pickup'),
 r("Night Maiden's Mist", "Gowry Shop", 'shop'),
 r("Night Shard", "Gowry Shop", 'shop'),
 r("Unseen Blade", "Mirage Rise", 'ground_pickup'),
 r("Unseen Form", "Mirage Rise", 'ground_pickup'),
 r("Comet Azur", "Primeval Sorcerer Azur", 'event'),
 r("Founding Rain of Stars", "Heretical Rise", 'ground_pickup'),
 r("Stars of Ruin", "Primeval Sorcerer Lusat", 'event'),
 r("Adula's Moonblade", "Glintstone Dragon Adula Drop", 'boss_drop'),
 r("Freezing Mist", "Preceptor Seluvis Shop", 'shop'),
 r("Frozen Armament", "Scarab Reward (Caria Manor)", 'enemy_drop'),
 r("Glintstone Icecrag", "Preceptor Seluvis Shop", 'shop'),
 r("Zamor Ice Storm", "Zamor Ruins", 'ground_pickup'),
 r("Whetstone Knife", "Gatefront Ruins", 'ground_pickup'),
 r("Iron Whetblade", "Stormveil Castle", 'ground_pickup'),
 r("Glintstone Whetblade", "Raya Lucaria Academy", 'ground_pickup'),
 r("Red-Hot Whetblade", "Redmane Castle", 'ground_pickup'),
 r("Black Whetblade", "Night's Sacred Ground", 'ground_pickup'),
 r("Sanctified Whetblade", "Leyndell, Royal Capital", 'ground_pickup'),
 r("Mighty Shot", "Scarab Reward (South Limgrave)", 'enemy_drop'),
 r("Parry", "Knight Bernahl Shop", 'shop'),
 r("No Skill", "Knight Bernahl Shop", 'shop'),
 r("Shield Crash", "Scarab Reward (Lux Ruins)", 'enemy_drop'),
 r("Storm Wall", "Scarab Reward (Stormhill)", 'enemy_drop'),
 r("Barrage", "Scarab Reward (Mt. Gelmir)", 'enemy_drop'),
 r("Enchanted Shot", "Scarab Reward (Nokron, Eternal City)", 'enemy_drop'),
 r("Barricade Shield", "Night's Cavalry (Weeping Peninsula), Bloodhound Knight Darriwil Drop", 'boss_drop'),
 r("Sky Shot", "Scarab Reward (Isolated Merchant Shack Dragonsbarrow)", 'enemy_drop'),
 r("Through and Through", "Scarab Reward (Mt. Gelmir)", 'enemy_drop'),
 r("Shield Bash", "Scarab Reward (East Gate Bridge Liurnia)", 'enemy_drop'),
 r("Rain of Arrows", "Redmane Painting Reward", 'event'),
 r("Repeating Thrust", "Limgrave", 'boss_drop'),
 r("Unsheathe", "Scarab Reward (Agheel Lake)", 'enemy_drop'),
 r("Quickstep", "Knight Bernahl Shop", 'shop'),
 r("Impaling Thrust", "Knight Bernahl Shop", 'shop'),
 r("Spinning Slash", "Knight Bernahl Shop", 'shop'),
 r("Sword Dance", "Scarab Reward (Liurnia Southwest Minor Erdtree)", 'enemy_drop'),
 r("Beast's Roar", "4th Deathroot Reward (Gurranq, Beast Clergyman)", 'event'),
 r("Bloudhound's Step", "Dragonsbarrow", 'boss_drop'),
 r("Double Slash", "Scarab Reward (Sellia, Town of Sorcery)", 'enemy_drop'),
 r("Raptor of the Mists", "Bloody Finger Ravenmount Assassin Drop", 'boss_drop'),
 r("Piercing Fang", "Bloody Finger Hunter Yura Drop", 'event'),
 r("Stamp (Sweep)", "Scarab Reward (West Limgrave Beach)", 'enemy_drop'),
 r("Stamp (Upward Cut)", "Knight Bernahl Shop", 'shop'),
 r("Kick", "Knight Bernahl Shop", 'shop'),
 r("Endure", "Knight Bernahl Shop", 'shop'),
 r("War Cry", "Knight Bernahl Shop", 'shop'),
 r("Wild Strikes", "Scarab Reward (North Limgrave Stormhill)", 'enemy_drop'),
 r("Ground Slam", "Scarab Reward (Limgrave Minor Erdtree)", 'enemy_drop'),
 r("Lion's Claw", "Fort Gael", 'enemy_drop'),
 r("Hoarah Loux's Earthshaker", "Remembrance of Hoarah Loux option", 'boss_drop'),
 r("Cragblade", "Scarab Reward (Impassable Bridge)", 'enemy_drop'),
 r("Barbaric Roar", "Scarab Reward (Ravine-Veiled Village)", 'enemy_drop'),
 r("Troll's Roar", "Church of Repose", 'ground_pickup'),
 r("Earthshaker", "Scarab Reward (Altus Plateau Highway)", 'enemy_drop'),
 r("Braggart's Roar", "Dung Eater Drop, Blackguard Big Boggart's Weapon", 'event'),
 r("Storm Blade", "Murkwater Catacombs", 'shop'),
 r("Storm Stomp", "Gatefront Ruins, Stormveil Castle", 'ground_pickup'),
 r("Storm Assault", "Scarab Reward (Stormveil Castle)", 'enemy_drop'),
 r("Stormcaller", "Scarab Reward (Stormveil Castle)", 'enemy_drop'),
 r("Determination", "Scarab Reward (Limgrave)", 'enemy_drop'),
 r("Charge Forth", "Scarab Reward (Academy Gate Town)", 'enemy_drop'),
 r("Square Off", "Scarab Reward (Siofra River)", 'enemy_drop'),
 r("Giant Hunt", "Northeast Liurnia", 'boss_drop'),
 r("Vacuum Slice", "Deeproot Depths", 'ground_pickup'),
 r("Spinning Strikes", "Edgar The Revenger's Weapon, Edgar's Weapon", 'boss_drop'),
 r("Royal Knight's Resolve", "Volcano Manor", 'ground_pickup'),
 r("Phantom Slash", "Forbidden Lands", 'boss_drop'),
 r("Gravitas", "Southwest Limgrave Beach", 'enemy_drop'),
 r("Spinning Weapon", "Sorcerer Rogier Shop", 'shop'),
 r("Carian Grandeur", "Caria Manor", 'ground_pickup'),
 r("Loretta's Slash", "Royal Knight Loretta Drop", 'boss_drop'),
 r("Waves of Darkness", "Remembrance of the Naturalborn option", 'boss_drop'),
 r("Hoarfrost Stomp", "Scarab Reward (Caria Manor Hill)", 'enemy_drop'),
 r("Chilling Mist", "Scarab Reward (Three Sisters)", 'enemy_drop'),
 r("Ice Spear", "Southeast Liurnia", 'boss_drop'),
 r("Flaming Strike", "Scarab Reward (Redmane Castle)", 'enemy_drop'),
 r("Eruption", "Knight Bernahl Shop (Volcano Manor)", 'shop'),
 r("Flame of the Redmanes", "Scarab Reward (Fort Gael)", 'enemy_drop'),
 r("Prelate's Charge", "Scarab Reward (Guardian's Garrison)", 'enemy_drop'),
 r("Black Flame Tornado", "Godskin Duo Drop", 'boss_drop'),
 r("Poison Moth Flight", "South Caelid", 'boss_drop'),
 r("Poisonous Mist", "Scarab Reward (Aeonia Swamp)", 'enemy_drop'),
 r("Bloody Slash", "Fort Haight (Limgrave)", 'ground_pickup'),
 r("Blood Blade", "Scarab Reward (Altus Plateau)", 'enemy_drop'),
 r("Seppuku", "Scarab Reward (Freezing Lake)", 'enemy_drop'),
 r("Blood Tax", "Mohgwyn Palace", 'ground_pickup'),
 r("Spectral Lance", "Scarab Reward (Raya Lucaria Academy)", 'enemy_drop'),
 r("Lifesteal Fist", "Scarab Reward (Caelid Highway)", 'enemy_drop'),
 r("Assassin's Gambit", "Knight Bernahl Shop (Volcano Manor)", 'shop'),
 r("White Shadow's Lure", "Scarab Reward (Consecrated Snowfields)", 'enemy_drop'),
 r("Lightning Slash", "Scarab Reward (Leyndell, Capital Outskirts)", 'enemy_drop'),
 r("Lightning Ram", "Scarab Reward (Altus Plateau)", 'enemy_drop'),
 r("Thunderbolt", "Scarab Reward (Leyndell, Royal Capital)", 'enemy_drop'),
 r("Golden Vow", "Limgrave", 'enemy_drop'),
 r("Sacred Blade", "Scarab Reward (Northeast Limgrave)", 'enemy_drop'),
 r("Sacred Order", "Scarab Reward (Altus Plateau)", 'enemy_drop'),
 r("Shared Order", "Altus Plateau", 'boss_drop'),
 r("Prayerful Strike", "Scarab Reward (Leyndell, Capital Outskirts)", 'enemy_drop'),
 r("Vow of the Indomitable", "Scarab Reward (Liurnia of the Lakes)", 'enemy_drop'),
 r("Sacred Ring of Light", "Scarab Reward (Aeonia Swamp)", 'enemy_drop'),
 r("Golden Slam", "Scarab Reward (Woodfolk Ruins)", 'enemy_drop'),
 r("Golden Land", "Scarab Reward (Deeproot Depths)", 'enemy_drop'),
 r("Golden Parry", "Scarab Reward (Leyndell, Capital Outskirts)", 'enemy_drop'),
 r("Holy Ground", "Auriza Hero's Grave", 'ground_pickup'),
 r("Wandering Noble", "Stormfoot Catacombs", 'ground_pickup'),
 r("Noble Sorcerer", "Stormfoot Catacombs", 'boss_drop'),
 r("Nomad", "Cathedral of the Forsaken", 'ground_pickup'),
 r("Putrid Corpses", "Gaol Cave", 'boss_drop'),
 r("Skeletal Militiaman", "Limgrave", 'boss_drop'),
 r("Skeletal Bandit", "Liurnia of the Lakes", 'boss_drop'),
 r("Albinauric", "Three Sisters", 'ground_pickup'),
 r("Winged Misbegotten", "Unsightly Catacombs", 'ground_pickup'),
 r("Demi-Human", "Impaler's Catacombs", 'boss_drop'),
 r("Clayman", "Ainsel River", 'ground_pickup'),
 r("Oracle Envoy", "Miquella's Haligtree", 'ground_pickup'),
 r("Lone Wolf", "Church of Elleh, Limgrave (Given by Renna)", 'event'),
 r("Rotten Stray", "Sellia, Town of Sorcery", 'ground_pickup'),
 r("Giant Rat", "West Windmill Pasture", 'ground_pickup'),
 r("Warhawk", "Prophecy Painting Reward", 'event'),
 r("Land Squirt", "Liurnia Lake", 'ground_pickup'),
 r("Jellyfish", "Stormhill Shack (Given by Roderika)", 'event'),
 r("Miranda Sprout", "Caelid Catacombs", 'ground_pickup'),
 r("Fanged Imp", "Isolated Merchant Shop (Main Academy Gate)", 'shop'),
 r("Soldjars of Fortune", "Grave Warden Duelist (Auriza Side Tomb)", 'boss_drop'),
 r("Archer", "Nokstella, Eternal City", 'ground_pickup'),
 r("Greatshield Soldier", "Nokron, Eternal City", 'ground_pickup'),
 r("Page", "Cliffbottom Catacombs", 'ground_pickup'),
 r("Vulgar Militia", "Auriza Hero's Grave", 'ground_pickup'),
 r("Marionette Soldier", "Raya Lucaria Academy", 'ground_pickup'),
 r("Avionette Soldier", "Raya Lucaria Academy", 'ground_pickup'),
 r("Kaiden Sellsword", "Cliffbottom Catacombs", 'boss_drop'),
 r("Mad Pumpkin Head", "Minor Erdtree Catacombs", 'boss_drop'),
 r("Fire Monk", "Giant's Mountaintops Catacombs", 'ground_pickup'),
 r("Ancestral Follower", "Ancestral Spirit Drop", 'boss_drop'),
 r("Azula Beastman", "Crumbling Farum Azula", 'ground_pickup'),
 r("Man-Serpent", "Volcano Manor", 'ground_pickup'),
 r("Crystalian", "Sellia Hideaway", 'ground_pickup'),
 r("Kindred of Rot", "Caelid Catacombs", 'boss_drop'),
 r("Glintstone Sorcerer", "Road's End Catacombs", 'boss_drop'),
 r("Twinsage Sorcerer", "Black Knife Catacombs", 'boss_drop'),
 r("Godrick Soldier", "Cemetary in Stormhill", 'ground_pickup'),
 r("Raya Lucaria Soldier", "Road's End Catacombs", 'ground_pickup'),
 r("Leyndell Soldier", "Sainted Hero's Grave", 'ground_pickup'),
 r("Radahn Soldier", "War-Dead Catacombs", 'ground_pickup'),
 r("Haligtree Soldier", "Elphael, Brace of the Haligtree", 'ground_pickup'),
 r("Mausoleum Soldier", "Deeproot Depths", 'ground_pickup'),
 r("Killed", "Attempts", 'ground_pickup'),
 r("REMEMBRANCES LIST", "CHOICE LIST", 'ground_pickup'),
 r("New Game +1", "New Game +2", 'ground_pickup'),
 r("New Game +4", "New Game +5", 'ground_pickup'),
 r("REMEMBRANCE OF THE NATURALBORN", "🏺Waves of Darkness", 'ground_pickup'),
 r("REMEMBRANCE OF THE REGAL ANCESTOR", "Winged Greathorn", 'ground_pickup'),
 r("REMEMBRANCE OF THE FIRE GIANT", "Giant’s Red Braid", 'ground_pickup'),
 r("REMEMBRANCE OF THE BLACK BLADE", "Maliketh’s Black Blade", 'ground_pickup'),
 r("REMEMBRANCE OF THE DRAGONLORD", "Dragon King’s Cragblade", 'ground_pickup'),
 r("REMEMBRANCE OF THE LICHDRAGON", "✨Death Lightning", 'ground_pickup'),
 r("REMEMBRANCE OF HOARAH LOUX", "Axe of Godfrey", 'ground_pickup'),
 r("ELDEN REMEMBRANCE", "Marika’s Hammer", 'ground_pickup'),
 r("REMEMBRANCE", "WORTH", 'ground_pickup'),
 r("Commoner's Headband", "Volcano Manor", 'ground_pickup'),
 r("Traveler's Manchettes", "Elphael, Brace of the Haligtree", 'ground_pickup'),
 r("Aristocrat Headband", "Noble Aristocrat Sorcerer Drop", 'enemy_drop'),
 r("Guardian Bracers", "Erdtree Guardian Drop", 'enemy_drop'),
 r("Aristocrat Hat", "Noble Aristocrat Soldier Drop", 'enemy_drop'),
 r("Bloodsoaked Manchettes", "Subterranean Shunning Grounds", 'ground_pickup'),
 r("Old Aristocrat Cowl", "Old Aristocrat Drop", 'enemy_drop'),
 r("Mushroom Arms", "Seethewater Cave", 'ground_pickup'),
 r("Page Hood", "Page Drop", 'enemy_drop'),
 r("Astrologer Gloves", "Nomadic Merchant Shop (South Liurnia)", 'shop'),
 r("High Page Hood", "High Page Drop", 'enemy_drop'),
 r("Sorcerer Manchettes", "Raya Lucaria Sorcerer Drop", 'enemy_drop'),
 r("Guardian Mask", "Erdtree Guardian Drop", 'enemy_drop'),
 r("Battlemage Manchettes", "Haima Battlemage Drop", 'enemy_drop'),
 r("Festive Hood", "Celebrant Drop", 'enemy_drop'),
 r("Errant Sorcerer Manchettes", "Hermit Village", 'ground_pickup'),
 r("Blue Festive Hood", "Celebrant Drop", 'enemy_drop'),
 r("Spellblade's Gloves", "Rogier's Corpse (Rogier's Questline)", 'event'),
 r("Guilty Hood", "Nomadic Merchant Shop (Mt. Gelmir)", 'shop'),
 r("Alberich's Bracers", "Fortified Manor (Leyndell, Royal Capital)", 'ground_pickup'),
 r("Prisoner Iron Mask", "Hermit Merchant Shop (Ainsel River)", 'shop'),
 r("Preceptor's Gloves", "Seluvis's Corpse", 'event'),
 r("Blackguard's Iron Mask", "Blackguard Big Boggart Drop", 'enemy_drop'),
 r("Azur's Manchettes", "Azur's Corpse (Sorceress Sellen Questline)", 'event'),
 r("Bloodsoaked Mask", "Subterranean Shunning Grounds", 'ground_pickup'),
 r("Lusat's Manchettes", "Lusat's Corpse (Sorceress Sellen Questline)", 'event'),
 r("Black Dumpling", "Albinauric Torturer Drop", 'enemy_drop'),
 r("Queen's Bracelets", "Enia Shop (Rennalla, Queen of the Full Moon Defeated)", 'shop'),
 r("Mushroom Head", "Seethewater Cave", 'ground_pickup'),
 r("Traveling Maiden Gloves", "Shack of the Lofty", 'ground_pickup'),
 r("Mushroom Crown", "Lake of Rot", 'ground_pickup'),
 r("Gold Bracelets", "Goldmask Corpse (Brother Corhyn Questline)", 'event'),
 r("Astrologer Hood", "Nomadic Merchant Shop (South Liurnia)", 'shop'),
 r("Perfumer Gloves", "Perfumer Drop", 'enemy_drop'),
 r("Juvenile Scholar Cap", "Resurrection Painting Reward", 'event'),
 r("Traveler's Gloves", "Street of Sages Ruins", 'ground_pickup'),
 r("Karolos Glintstone Crown", "Raya Lucaria Academy", 'enemy_drop'),
 r("Depraved Perfumer Gloves", "Depraved Perfumer Drop", 'enemy_drop'),
 r("Olivinus Glintstone Crown", "Raya Lucaria Academy", 'ground_pickup'),
 r("Godskin Apostle Bracelets", "Divine Tower of Caelid", 'boss_drop'),
 r("Twinsage Glintstone Crown", "Raya Lucaria Academy", 'enemy_drop'),
 r("Godskin Noble Bracelets", "Divine Tower of Liurnia", 'enemy_drop'),
 r("Witch's Glintstone Crown", "Sorceress Sellen Questline", 'event'),
 r("Leather Gloves", "Murkwater Cave", 'ground_pickup'),
 r("Lazuli Glintstone Crown", "Raya Lucaria Academy", 'ground_pickup'),
 r("Warrior Gauntlets", "Isolated Merchant Shop (Main Academy Gate)", 'shop'),
 r("Haima Glintstone Crown", "Haima Battlemage Drop", 'enemy_drop'),
 r("Noble's Gloves", "East Windmill Pasture", 'ground_pickup'),
 r("Hierodas Glintstone Crown", "Hermit Village", 'ground_pickup'),
 r("War Surgeon Gloves", "Nameless White Mask Drop", 'enemy_drop'),
 r("Spellblade's Pointed Hat", "Rogier's Corpse (Rogier's Questline)", 'event'),
 r("Bandit Manchettes", "Nomadic Merchant Shop (North Limgrave)", 'shop'),
 r("Alberich's Pointed Hat", "Fortified Manor (Leyndell, Royal Capital)", 'ground_pickup'),
 r("Confessor Gloves", "Nomadic Merchant Shop (Mt. Gelmir)", 'shop'),
 r("Preceptor's Big Hat", "Seluvis's Corpse (Ranni Questline)", 'event'),
 r("Omenkiller Long Gloves", "Perfumer Ruins", 'enemy_drop'),
 r("Mask of Confidence", "Carian Study Hall (Inverted)", 'ground_pickup'),
 r("Foot Soldier Gauntlets", "Foot Soldier Drop", 'enemy_drop'),
 r("Azur's Glintstone Crown", "Azur's Corpse (Sorceress Sellen Questline)", 'event'),
 r("Highwayman Gauntlets", "Murkwater Cave", 'enemy_drop'),
 r("Lusat's Glintstone Crown", "Lusat's Corpse (Sorceress Sellen Questline)", 'event'),
 r("Vulgar Militia Gauntlets", "Vulgar Militiamen Drop", 'enemy_drop'),
 r("Queen's Crescent Crown", "Enia Shop (Rennalla, Queen of the Full Moon Defeated)", 'shop'),
 r("Nox Monk Bracelets", "Nox Priest Drop", 'enemy_drop'),
 r("Snow Witch Hat", "Renna's Rise", 'ground_pickup'),
 r("Champion Bracers", "Nomadic Merchant Shop (South Caelid)", 'shop'),
 r("Fia's Hood", "Fia's Corpse (Fia's Questine)", 'event'),
 r("Prophet Blindfold", "Hermit Merchant Shop (Leyndell, Capital Outskirts)", 'shop'),
 r("Iron Gauntlets", "Nomadic Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Traveling Maiden Hood", "Shack of the Lofty", 'ground_pickup'),
 r("Godrick Soldier Gauntlets", "Godrick Soldier Drop", 'enemy_drop'),
 r("Finger Maiden Fillet", "Church of Inhibition", 'ground_pickup'),
 r("Raya Lucarian Gauntlets", "Raya Lucarian Soldier Drop", 'enemy_drop'),
 r("Sage Hood", "Stillwater Cave", 'ground_pickup'),
 r("Radahn Soldier Gauntlets", "Radahn Soldier Drop", 'enemy_drop'),
 r("Greathood", "Sorcerer Painting Reward", 'event'),
 r("Leyndell Soldier Gauntlets", "Leyndell Soldier Drop", 'enemy_drop'),
 r("Radiant Gold Mask", "Forest Spanning Bridge (Altus Plateau)", 'ground_pickup'),
 r("Haligtree Gauntlets", "Haligtree Soldier Drop", 'enemy_drop'),
 r("Perfumer Hood", "Perfumer Drop", 'enemy_drop'),
 r("Mausoleum Gauntlets", "Mausoleum Soldier Drop", 'enemy_drop'),
 r("Traveler's Hat", "Street of Sages Ruins", 'ground_pickup'),
 r("Exile Gauntlets", "Castle Guard Drop", 'enemy_drop'),
 r("Depraved Perfumer Headscarf", "Depraved Perfumer Drop", 'enemy_drop'),
 r("Kaiden Gauntlets", "Kaiden Sellsword Drop", 'enemy_drop'),
 r("Ruler's Mask", "Abandoned Coffin (Altus Plateau)", 'ground_pickup'),
 r("Land of Reeds Gauntlets", "Hermit Merchant Shop (Caelid, Dragonsbarrow)", 'shop'),
 r("Consort's Mask", "Tanith Drop", 'enemy_drop'),
 r("White Reed Gauntlets", "Bloody Finger Okina Drop", 'boss_drop'),
 r("Marais Mask", "Maleigh Marais Drop", 'boss_drop'),
 r("Ronin's Gauntlets", "Shabriri Drop", 'enemy_drop'),
 r("Great Horned Headband", "Ancestral Follower Drop", 'enemy_drop'),
 r("Eccentric's Manchettes", "Sellen Questline, Ally", 'enemy_drop'),
 r("Shining Horned Headband", "Ancestral Follower Shaman Drop", 'enemy_drop'),
 r("Blue Silver Bracelets", "Albinauric Archer Drop", 'enemy_drop'),
 r("Godskin Apostle Hood", "Divine Tower of Caelid", 'boss_drop'),
 r("Fire Monk Gauntlets", "Fire Monk Drop", 'enemy_drop'),
 r("Godskin Noble Hood", "Divine Tower of Liurnia", 'enemy_drop'),
 r("Blackflame Monk Gauntlets", "Blackflame Monk Drop", 'enemy_drop'),
 r("Sanguine Noble Hood", "Snowfields", 'boss_drop'),
 r("Zamor Bracelets", "Giant-Conquering Hero's Grave", 'boss_drop'),
 r("Crimson Tear Scarab", "Volcano Manor", 'ground_pickup'),
 r("Black Knife Gauntlets", "Ordina Liturgical Town", 'ground_pickup'),
 r("Cerulean Tear Scarab", "Sellia, Town of Sorcery", 'ground_pickup'),
 r("Malenia's Gauntlet", "Enia Shop (Malenia, Blade of Miquella Defeated)", 'shop'),
 r("Ash-of-War Scarab", "Limgrave Tower Bridge", 'ground_pickup'),
 r("Elden Lord Bracers", "Enia Shop (Godfrey, First Elden Lord Defeated)", 'shop'),
 r("Glintstone Scarab", "Raya Lucaria Academy", 'ground_pickup'),
 r("Knight Gauntlets", "Twin Maiden Husk Shop", 'shop'),
 r("Incantation Scarab", "Homing Instinct Painting Reward", 'event'),
 r("Vagabond Knight Gauntlets", "Nomadic Merchant Shop (Mountaintops)", 'shop'),
 r("Imp Head (Cat)", "Limgrave Catacomb Locations", 'enemy_drop'),
 r("Carian Knight Gauntlets", "Raya Lucaria Academy", 'ground_pickup'),
 r("Imp Head (Corpse)", "Leyndell, Royal Capital", 'ground_pickup'),
 r("Godrick Knight Gauntlets", "Godrick Knight Drop", 'enemy_drop'),
 r("Imp Head (Elder)", "Consecrated Snowfield Catacombs", 'ground_pickup'),
 r("Cuckoo Knight Gauntlets", "Cuckoo Knight Drop", 'enemy_drop'),
 r("Imp Head (Long-Tongued)", "Subterranean Shunning Grounds", 'enemy_drop'),
 r("Redmane Knight Gauntlets", "Redmane Knight Drop", 'enemy_drop'),
 r("Imp Head (Wolf)", "Minor Erdtree Catacombs", 'ground_pickup'),
 r("Gelmir Knight Gauntlets", "Gelmir Hero's Grave", 'ground_pickup'),
 r("Imp Head (Fanged)", "Imp Drop", 'enemy_drop'),
 r("Leyndell Knight Gauntlets", "Leyndell Knight Drop", 'enemy_drop'),
 r("Nox Mirrorhelm", "Cliffbottom Catacombs", 'ground_pickup'),
 r("Haligtree Knight Gauntlets", "Haligtree Knight Drop", 'enemy_drop'),
 r("Iji's Mirrorhelm", "Iji's Corpse (Ranni Questline)", 'event'),
 r("Mausoleum Knight Gauntlets", "Mausoleum Knight Drop", 'enemy_drop'),
 r("Silver Tear Mask", "Mimic Tear Drop", 'boss_drop'),
 r("Bloodhound Knight Gauntlets", "Gelmir Hero's Grave", 'enemy_drop'),
 r("Envoy Crown", "Miquella's Haligtree", 'ground_pickup'),
 r("Cleanrot Gauntlets", "Cleanrot Knight Drop", 'enemy_drop'),
 r("Octopus Head", "Land Octopus Drop, Giant Land Octopus Drop", 'enemy_drop'),
 r("Raging Wolf Gauntlets", "Vargram the Raging Wolf Drop", 'boss_drop'),
 r("Jar", "Iron Fist Alexander Questline", 'event'),
 r("Hoslow's Gauntlets", "Juno Hoslow Drop", 'boss_drop'),
 r("Albinauric Mask", "Volcano Manor", 'ground_pickup'),
 r("Twinned Gauntlets", "D Drop, D Questline", 'event'),
 r("Black Wolf Mask", "Seluvis's Rise", 'ground_pickup'),
 r("Drake Knight Gauntlets", "Crumbling Farum Azula", 'ground_pickup'),
 r("Blue Cloth Cowl", "Isolated Merchant Shop (Main Academy Gate)", 'shop'),
 r("Blaidd's Gauntlets", "Blaidd Drop (Ranni Questline", 'event'),
 r("Crimson Hood", "Stormveil Castle", 'ground_pickup'),
 r("Briar Gauntlets", "Enia Shop (Elemer of the Briar Defeated)", 'shop'),
 r("Navy Hood", "East Windmill Pasture", 'ground_pickup'),
 r("Fingerprint Gauntlets", "Roundtable Knight Vyke Drop", 'boss_drop'),
 r("White Mask", "Nameless White Mask Drop", 'enemy_drop'),
 r("Royal Remains Gauntlets", "Ensha of the Royal Remains Drop", 'boss_drop'),
 r("Nomadic Merchant's Chapeau", "Cathedral of the Forsaken", 'ground_pickup'),
 r("All-Knowing Gauntlets", "Sir Gideon Ofnir, The All Knowing Drop", 'boss_drop'),
 r("Bandit Mask", "Nomadic Merchant Shop (North Limgrave)", 'shop'),
 r("Royal Knight Gauntlets", "Enia Shop (Loretta, Knight of the Haligtree Defeated)", 'shop'),
 r("Black Hood", "Sages Cave", 'ground_pickup'),
 r("Maliketh's Gauntlets", "Enia Shop (Maliketh, The Black Blade Defeated)", 'shop'),
 r("Confessor Hood", "Nomadic Merchant Shop (Mt. Gelmir)", 'shop'),
 r("Banished Knight Gauntlets", "Banished Knight Drop", 'enemy_drop'),
 r("Omensmirk Mask", "Leyndell, Royal Capital", 'ground_pickup'),
 r("Night's Cavalry Gauntlets", "Night Cavalry Duo Drop", 'boss_drop'),
 r("Skeletal Mask", "Sages Cave", 'ground_pickup'),
 r("Veteran's Gauntlets", "Enia Shop (Commander Niall Defeated)", 'shop'),
 r("Foot Soldier Helm", "Radahn Foot Soldier Drop", 'enemy_drop'),
 r("Scaled Gauntlets", "Old Knight Istvan Drop", 'boss_drop'),
 r("Foot Soldier Helmet", "Liurnia Foot Soldier Drop", 'enemy_drop'),
 r("Beast Champion Gauntlets", "Bernahl at Volcano Manor", 'boss_drop'),
 r("Foot Soldier Cap", "Limgrave Foot Soldier Drop", 'enemy_drop'),
 r("Tree Sentinels Gauntlets", "Auriza Hero's Grave", 'ground_pickup'),
 r("Gilded Foot Soldier Cap", "Leyndell Foot Soldier Drop", 'enemy_drop'),
 r("Malformed Dragon Gauntlets", "Crumbling Farum Azula", 'enemy_drop'),
 r("Sacred Crown Helm", "Haligtree Foot Soldier Drop", 'enemy_drop'),
 r("Crucible Gauntlets", "Crucible Knight Ordovis Drop, Crucible Knight Siluria Drop", 'boss_drop'),
 r("Highwayman Hood", "Murkwater Cave", 'enemy_drop'),
 r("Radahn's Gauntlets", "Enia Shop (Starscourge Radahn Defeated)", 'shop'),
 r("Vulgar Militia Helm", "Vulgar Militiamen Drop", 'enemy_drop'),
 r("Lionel's Gauntlets", "Leyndell, Royal Capital", 'ground_pickup'),
 r("Duelist Helm", "Duelist Drop", 'enemy_drop'),
 r("Bull-Goat Gauntlets", "Great Horned Tragoth Drop", 'boss_drop'),
 r("Rotten Duelist Helm", "Consecrated Snowfields", 'enemy_drop'),
 r("Omen Gauntlets", "Dung Eater Drop", 'enemy_drop'),
 r("Nox Monk Hood", "Nox Priest Drop", 'enemy_drop'),
 r("Fire Prelate Gauntlets", "Fire Prelate Drop", 'enemy_drop'),
 r("Nox Swordstress Crown", "Nox Swordstress Drop", 'enemy_drop'),
 r("Night Maiden Twin Crown", "Night Maiden Drop", 'enemy_drop'),
 r("Champion Headband", "Nomadic Merchant Shop (South Caelid)", 'shop'),
 r("Chain Coif", "Kale Shop", 'enemy_drop'),
 r("Iron Helmet", "Nomadic Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Godrick Soldier Helm", "Godrick Soldier Drop", 'enemy_drop'),
 r("Raya Lucarian Helm", "Raya Lucarian Soldier Drop", 'enemy_drop'),
 r("Radahn Soldier Helm", "Radahn Soldier Drop", 'enemy_drop'),
 r("Leyndell Soldier Helm", "Leyndell Soldier Drop", 'enemy_drop'),
 r("Haligtree Helm", "Haligtree Soldier Drop", 'enemy_drop'),
 r("Exile Hood", "Castle Guard Drop", 'enemy_drop'),
 r("Kaiden Helm", "Kaiden Sellsword Drop", 'enemy_drop'),
 r("Land of Reeds Helm", "Hermit Merchant Shop (Caelid, Dragonsbarrow)", 'shop'),
 r("Okina Mask", "Bloody Finger Okina Drop", 'boss_drop'),
 r("Iron Kasa", "Shabriri Drop", 'enemy_drop'),
 r("Eccentric's Hood", "Sellen Questline, Ally", 'enemy_drop'),
 r("Marionette Soldier Helm", "Marionette Soldier Drop", 'enemy_drop'),
 r("Marionette Soldier Birdhelm", "Avionette Soldier Drop", 'enemy_drop'),
 r("Blue Silver Mail Hood", "Albinauric Archer Drop", 'enemy_drop'),
 r("Fire Monk Hood", "Fire Monk Drop", 'enemy_drop'),
 r("Blackflame Monk Hood", "Blackflame Monk Drop", 'enemy_drop'),
 r("Zamor Mask", "Giant-Conquering Hero's Grave", 'boss_drop'),
 r("Black Knife Hood", "Ordina Liturgical Town", 'ground_pickup'),
 r("Malenia's Winged Helm", "Enia Shop (Malenia, Blade of Miquella Defeated)", 'shop'),
 r("Elden Lord Crown", "Enia Shop (Godfrey, First Elden Lord Defeated)", 'shop'),
 r("Knight Helm", "Twin Maiden Husks Shop", 'shop'),
 r("Vagabond Knight Helm", "Nomadic Merchant Shop (Mountaintops)", 'shop'),
 r("Greathelm", "Nomadic Merchant Shop (South Caelid)", 'shop'),
 r("Carian Knight Helm", "Raya Lucaria Academy", 'ground_pickup'),
 r("Godrick Knight Helm", "Godrick Knight Drop", 'enemy_drop'),
 r("Cuckoo Knight Helm", "Cuckoo Knight Drop", 'enemy_drop'),
 r("Redmane Knight Helm", "Redmane Knight Drop", 'enemy_drop'),
 r("Gelmir Knight Helm", "Gelmir Hero's Grave", 'ground_pickup'),
 r("Leyndell Knight Helm", "Leyndell Knight Drop", 'enemy_drop'),
 r("Haligtree Knight Helm", "Haligtree Knight Drop", 'enemy_drop'),
 r("Bloodhound Knight Helm", "Gelmir Hero's Grave", 'enemy_drop'),
 r("Cleanrot Helm", "Cleanrot Knight Drop", 'enemy_drop'),
 r("Raging Wolf Helm", "Vargram the Raging Wolf Drop", 'boss_drop'),
 r("Hoslow's Helm", "Juno Hoslow Drop", 'boss_drop'),
 r("Diallos's Mask", "Daillos Drop, Daillos Questline", 'event'),
 r("Twinned Helm", "D Drop, D Questline", 'event'),
 r("Drake Knight Helm", "Crumbling Farum Azula", 'ground_pickup'),
 r("Briar Helm", "Enia Shop (Elemer of the Briar Defeated)", 'shop'),
 r("Fingerprint Helm", "Roundtable Knight Vyke Drop", 'boss_drop'),
 r("Royal Remains Helm", "Ensha of the Royal Remains Drop", 'boss_drop'),
 r("All-Knowing Helm", "Sir Gideon Ofnir, The All Knowing Drop", 'boss_drop'),
 r("Royal Knight Helm", "Enia Shop (Loretta, Knight of the Haligtree Defeated)", 'shop'),
 r("Maliketh's Helm", "Enia Shop (Maliketh, The Black Blade Defeated)", 'shop'),
 r("Banished Knight Helm", "Banished Knight Drop", 'enemy_drop'),
 r("Night's Cavalry Helm", "Night Cavalry Duo Drop", 'boss_drop'),
 r("Veteran's Helm", "Enia Shop (Commander Niall Defeated)", 'shop'),
 r("Scaled Helm", "Old Knight Istvan Drop", 'boss_drop'),
 r("Beast Champion Helm", "Bernahl at Volcano Manor", 'boss_drop'),
 r("Tree Sentinel Helm", "Auriza Hero's Grave", 'ground_pickup'),
 r("Malformed Dragon Helm", "Crumbling Farum Azula", 'enemy_drop'),
 r("Crucible Axe Helm", "Crucible Knight Ordovis Drop", 'boss_drop'),
 r("Crucible Tree Helm", "Crucible Knight Siluria Drop", 'boss_drop'),
 r("Radahn's Redmane Helm", "Enia Shop (Starscourge Radahn Defeated)", 'shop'),
 r("Lionel's Helm", "Leyndell, Royal Captial", 'ground_pickup'),
 r("Bull-Goat Helm", "Great Horned Tragoth Drop", 'boss_drop'),
 r("Omen Helm", "Dung Eater Drop", 'enemy_drop'),
 r("Fire Prelate Helm", "Fire Prelate Drop", 'enemy_drop'),
 r("Pumpkin Helm", "Mad Pumpkin Head Drop", 'enemy_drop'),
 r("TALISMANS", "EFFECT", 'ground_pickup'),
 r("Crimson Seed Talisman", "Restore 20% More Health Points from Crimson Flasks", 'ground_pickup'),
 r("Crepus's Vial", "Eliminates sound made by the wearer's movements", 'ground_pickup'),
 r("Concealing Veil", "Conceals the wearer when crouched away from foes", 'ground_pickup'),
 r("Longtail Cat Talisman", "Negates all Non-Lethal Fall Damage", 'ground_pickup'),
 r("Furled Finger's Trick Mirror", "Take on the appearance of the Host of Fingers", 'ground_pickup'),
 r("Host's Trick Mirror", "Take on the appearance of a Cooperator", 'ground_pickup'),
 r("Shabriri's Woe", "Constantly attracts enemies aggression", 'ground_pickup'),
 r("Sacrificial Twig", "Will be lost on Death instead of Runes", 'ground_pickup'),
 r("Sacrificial Twig #1", "Patches Shop", 'shop'),
 r("Sacrificial Twig #2", "Mistwood (Limgrave)", 'ground_pickup'),
 r("Sacrificial Twig #3", "Isolated Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Sacrificial Twig #4", "Isolated Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Sacrificial Twig #5", "Isolated Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Sacrificial Twig #6", "Given by Edgar (Castle Morne)", 'event'),
 r("Sacrificial Twig #7", "Given by Fia (Rogier Dialogue, Rogier Questline)", 'event'),
 r("Sacrificial Twig #8", "South Liurnia of the Lakes", 'ground_pickup'),
 r("Sacrificial Twig #9", "Isolated Merchant Shop (Main Academy Gate)", 'shop'),
 r("Sacrificial Twig #10", "Isolated Merchant Shop (Main Academy Gate)", 'shop'),
 r("Sacrificial Twig #11", "Isolated Merchant Shop (Main Academy Gate)", 'shop'),
 r("Sacrificial Twig #12", "Altus Plateau (Soldier Camp)", 'ground_pickup'),
 r("Sacrificial Twigs", "Altus Plateau, Crumbling Farum Azula", 'enemy_drop'),
 r("Flask of Crimson Tears", "Automatically Received", 'starting_loadout'),
 r("Flask of Cerulean Tears", "Automatically Received", 'starting_loadout'),
 r("Flask of Wondrous Physick", "Third Church of Marika", 'ground_pickup'),
 r("Memory of Grace", "Automatically Received", 'starting_loadout'),
 r("Spectral Steed Whistle", "Given by Melina at Stormgate", 'event'),
 r("Lantern", "Isolated Merchant Shop (Weeping Peninsula)", 'shop'),
 r("Telescope", "Kale Shop", 'shop'),
 r("Crafting Kit", "Kale Shop", 'shop'),
 r("Spirit Calling Bell", "Given by Renna at Church of Elleh", 'event'),
 r("Tailoring Tools", "Demihuman Chief Duo Drop", 'boss_drop'),
 r("Golden Tailoring Tools", "Church of Vows", 'ground_pickup'),
 r("Wraith Calling Bell", "Laskyar Ruins", 'ground_pickup'),
 r("Ancestral Infant's Head", "Nokron, Eternal City", 'ground_pickup'),
 r("Omen Bairn", "Subterranean Shunning Grounds", 'enemy_drop'),
 r("Regal Omen Bairn", "Remembrance of the Omen King option", 'boss_drop'),
 r("Mimic's Veil", "Stormveil Castle", 'ground_pickup'),
 r("Margit's Shackle", "Patches Shop", 'shop'),
 r("Mohg's Shackle", "Subterranean Shunning Grounds", 'ground_pickup'),
 r("Blasphemous Claw", "Bernahl at Volcano Manor", 'boss_drop'),
 r("Pureblood Knights Medal", "White Faced Varre Questline", 'event'),
 r("Prattling Pate \"Hello\"", "Stormfoot Catacombs", 'ground_pickup'),
 r("Prattling Pate \"Thank You\"", "Tombsward Catacombs", 'ground_pickup'),
 r("Prattling Pate \"Apologies\"", "Unsightly Catacombs", 'ground_pickup'),
 r("Prattling Pate \"Wonderful\"", "Cliffbottom Catacombs", 'ground_pickup'),
 r("Prattling Pate \"Please Help\"", "Impaler's Catacombs", 'ground_pickup'),
 r("Prattling Pate \"My Beloved\"", "Miquella's Haligtree", 'ground_pickup'),
 r("Prattling Pate \"Let's Get To It\"", "Sainted Hero's Grave", 'ground_pickup'),
 r("Prattling Pate \"You're Beautiful\"", "Hermit Village", 'ground_pickup'),
 r("Talisman Pouch #1", "Margit the Fell Omen Drop", 'boss_drop'),
 r("Talisman Pouch #2", "Given by Enia after obtaining 2 Great Runes", 'event'),
 r("Talisman Pouch #3", "Godfrey, First Elden Lord Drop", 'boss_drop'),
 r("Tarnished Furled Finger", "Chapel of Anticipation (Start of Game)", 'ground_pickup'),
 r("Duelist's Furled Finger", "North Limgrave", 'ground_pickup'),
 r("Bloody Finger", "White Faced Varre Questline", 'event'),
 r("Recusant Finger", "Volcano Manor", 'ground_pickup'),
 r("White Cipher Ring", "Twin Maiden Husks Shop", 'shop'),
 r("Blue Cipher Ring", "Twin Maiden Husks Shop", 'shop'),
 r("Taunter's Tongue", "Mad Tongue Alberich Drop", 'boss_drop'),
 r("Finger Severer", "Chapel of Anticipation (Start of Game)", 'ground_pickup'),
 r("Tarnished Wizened Finger", "Stranded Graveyard (Start of Game)", 'ground_pickup'),
 r("Godrick's Great Rune", "Godrick the Grafted Drop", 'boss_drop'),
 r("Radahn's Great Rune", "Starscourge Radahn Drop", 'boss_drop'),
 r("Rykard's Great Rune", "Rykard, Lord of Blasphemy Drop", 'boss_drop'),
 r("Morgott's Great Rune", "Morgott, the Omen King Drop", 'boss_drop'),
 r("Mohg's Great Rune", "Mohg, Lord of Blood Drop", 'boss_drop'),
 r("Malenia's Great Rune", "Malenia, Goddess of Rot Drop", 'boss_drop'),
 r("Great Rune of the Unborn", "Rennala, Queen of the Full Moon Drop", 'boss_drop'),
 r("Mending Rune of Perfect Order", "Brother Corhyn Questline", 'event'),
 r("Mending Rune of the Death Prince", "Fia, Deathbed Companion Questline", 'event'),
 r("Mending Rune of the Fell Curse", "Dung Eater Questline", 'event'),
 r("Assassin's Prayerbook", "Roundtable Hold", 'ground_pickup'),
 r("Godskin Prayerbook", "Stormveil Castle", 'ground_pickup'),
 r("Fire Monk's Prayerbook", "Liurnia of the Lakes (Fire Monk Outpost)", 'ground_pickup'),
 r("Giant's Prayerbook", "Guardian's Garrison (Mountaintops)", 'ground_pickup'),
 r("Two Finger's Prayerbook", "Leyndell Royal Capital (Fortified Manor)", 'ground_pickup'),
 r("Dragon Cult Prayerbook", "near Artist Shack", 'enemy_drop'),
 r("Ancient Dragon's Prayerbook", "Crumbling Farum Azula (Tempest Facing Balcony)", 'ground_pickup'),
 r("Golden Order Principia", "Erdtree Sanctuary (Leyndell Royal Capital)", 'ground_pickup'),
 r("Point Forwards", "Automatically Received", 'starting_loadout'),
 r("Point Upwards", "Automatically Received", 'starting_loadout'),
 r("Point Downwards", "Automatically Received", 'starting_loadout'),
 r("Wait", "Automatically Received", 'starting_loadout'),
 r("Calm Down", "Patches Questline", 'event'),
 r("Wave", "Automatically Received", 'starting_loadout'),
 r("Beckon", "Automatically Received", 'starting_loadout'),
 r("Casual Greeting", "Summoning Great Horned Tragoth (Makar or Radahn)", 'event'),
 r("Warm Welcome", "Automatically Received", 'starting_loadout'),
 r("Bravo", "First Step Message after slayed a Demigod", 'ground_pickup'),
 r("Strength", "Tutorial Cave", 'ground_pickup'),
 r("Jump for Joy", "Automatically Received", 'starting_loadout'),
 r("Triumphant Delight", "Iron Fist Alexander Questline", 'event'),
 r("Fancy Spin", "Stargazer Ruins solution", 'event'),
 r("Nod in Thought", "Meeting Sorceress Sellen", 'event'),
 r("Finger Snap", "Merchant Kale dialogue (Mistwood)", 'event'),
 r("Rallying Cry", "Automatically Received", 'starting_loadout'),
 r("Heartening Cry", "Meeting Witch-Hunter Jerren", 'event'),
 r("Bow", "Automatically Received", 'starting_loadout'),
 r("Polite Bow", "Meeting Finger Maiden Thorelina (Redmane Castle)", 'event'),
 r("As you Wish", "Hyetta Questline", 'event'),
 r("My Thanks", "Volcano Manor (post Rykard)", 'ground_pickup'),
 r("Curtsy", "Roderika Questline, Ashes to +4 and dialogue", 'event'),
 r("Reverential Bow", "Before fight with Mad Tongue Alberich", 'event'),
 r("My Lord", "Boc The Seamster Questline", 'event'),
 r("What do you Want?", "Meeting Ensha at Roundtable", 'event'),
 r("By my Sword", "Fortified Manor (Leyndell)", 'ground_pickup'),
 r("Hoslow's Oath", "Before fight with Juno Hoslow", 'event'),
 r("Fire Spur Me", "Fire Monk camp near Church of Vows", 'ground_pickup'),
 r("The Ring", "Pre-Ordering the game, or beating a boss with someone who did", 'shop'),
 r("Erudition", "Thops Questline", 'event'),
 r("Prayer", "Meeting Brother Corhyn", 'event'),
 r("Desperate Prayer", "Gowry Questline, Buy Pest Threads and dialogue", 'shop'),
 r("Rapture", "Meeting Two Fingers at Roundtable", 'event'),
 r("Inner Order", "D Questline, Siofra Aqueduct", 'event'),
 r("Outer Order", "Melina dialogue (Minor Erdtree Church)", 'event'),
 r("Golden Order Totality", "Brother Corhyn Questline (Goldmask solution)", 'event'),
 r("Extreme Repentance", "Befriend Patches, let him beat you to low HP, Grovel for Mercy", 'event'),
 r("Grovel for Mercy", "When Patches surrenders", 'event'),
 r("Crossed Legs", "near Stormhill Shack", 'ground_pickup'),
 r("Dozing Cross-legged", "Stormveil Rooftops", 'ground_pickup'),
 r("Rest", "Automatically Received", 'starting_loadout'),
 r("Sitting Sideways", "Meeting Roderika", 'event'),
 r("Dejection", "Automatically Received", 'starting_loadout'),
 r("Patches Crouch", "Patches Questline (Very End)", 'event'),
 r("Balled Up", "Rebirthing from Rennalla", 'event'),
 r("Spread Out", "Buying Boiled Prawns from Blackguard", 'shop'),
 r("Limgrave West", "Gatefront Ruins", 'ground_pickup'),
 r("Limgrave East", "Mistwood", 'ground_pickup'),
 r("Weeping Peninsula", "Weeping Peninsula", 'ground_pickup'),
 r("Liurnia East", "Southeast Liurnia", 'ground_pickup'),
 r("Liurnia West", "Northwest Liurnia", 'ground_pickup'),
 r("Liurnia North", "Academy Gate Town", 'ground_pickup'),
 r("Caelid", "Central Caelid", 'ground_pickup'),
 r("Dragonsbarrow", "North Caelid", 'ground_pickup'),
 r("Altus Plateau", "Altus Highway", 'ground_pickup'),
 r("Mt. Gelmir", "Road of Iniquity", 'ground_pickup'),
 r("Leyndell, Royal Capital", "Leyndell, Capital Outskirts", 'ground_pickup'),
 r("Mountaintops of the Giants West", "Mountaintops of the Giants", 'ground_pickup'),
 r("Mountaintops of the Giants East", "Flame Peak", 'ground_pickup'),
 r("Consecrated Snowfields", "Frozen River", 'ground_pickup'),
 r("Siofra River", "Siofra River", 'ground_pickup'),
 r("Ainsel River", "Ainsel River", 'ground_pickup'),
 r("Lake of Rot", "Lake of Rot", 'ground_pickup'),
 r("Deeproot Depths", "Deeproot Depths", 'ground_pickup'),
 r("Mohgwyn Palace", "Mohgwyn Dynasty Mausoleum", 'ground_pickup'),
 r("Seedbed Curse #1", "Leyndell, Royal Capital", 'ground_pickup'),
 r("Seedbed Curse #2", "Leyndell, Royal Capital", 'ground_pickup'),
 r("Seedbed Curse #3", "Leyndell, Capital Outskirts, Blackguards Questline", 'event'),
 r("Seedbed Curse #4", "Volcano Manor", 'ground_pickup'),
 r("Seedbed Curse #5", "Elphael, Brace of the Haligtree", 'ground_pickup'),
 r("Seedbed Curse #6", "Elphael, Brace of the Haligtree", 'ground_pickup'),
 r("Shabriri Grape #1", "Stormveil Castle back exit", 'ground_pickup'),
 r("Shabriri Grape #2", "Purified Ruins", 'ground_pickup'),
 r("Shabriri Grape #3", "Irina & Edgar Questline, Edgar Drop, Edgar The Revenger Drop", 'boss_drop'),
 r("Fingerprint Grape", "Festering Fingerprint Vyke Drop", 'boss_drop'),
 r("Fingerslayer Blade", "Nokron, Eternal City", 'ground_pickup'),
 r("Carian Inverted Statue", "Given by Ranni after giving Fingerslayer Blade", 'event'),
 r("Cursemark of Death", "Divine Tower of Liurnia", 'ground_pickup'),
 r("Miniature Ranni", "Ainsel River Main", 'ground_pickup'),
 r("Dark Moon Ring", "Grand Library (Raya Lucaria Academy)", 'ground_pickup'),
 r("Beast Eye", "Given by Gurranq, Beastman Clergyman", 'event'),
 r("Weathered Dagger", "Given by Fia after arrival at Altus Plateau", 'event'),
 r("Black Knife Print", "Black Knife Catacombs", 'boss_drop'),
 r("Seluvis's Introduction", "Seluvis Questline, Given after meeting Seluvis", 'event'),
 r("Seluvis's Potion", "Seluvis Questline, Given after meeting Seluvis", 'event'),
 r("Amber Starlight", "Altus Plateau", 'ground_pickup'),
 r("Amber Draught", "Seluvis Questline, after giving Amber Starlight", 'event'),
 r("Iji's Confession", "Iji's Corpse, Blaidd Questline", 'event'),
 r("Sellen's Primal Glintstone", "Sellen Questline", 'event'),
 r("Rya's Necklace", "Rya Questline, Blackguard Shop", 'shop'),
 r("Volcano Manor Invitation", "Rya Questline, after giving Rya's Necklace", 'event'),
 r("Serpent's Amnion", "Temple of Eiglay", 'ground_pickup'),
 r("Tonic of Forgetfulness", "Rya Questline, Given by Tanith", 'event'),
 r("Dancer's Castanets", "Given by Patches at Shaded Castle after Rykard", 'event'),
 r("Unalloyed Golden Needle", "Commander O'Neil Drop", 'boss_drop'),
 r("Valkarie's Prosthesis", "The Shaded Castle", 'ground_pickup'),
 r("Miquella's Needle", "Millicent's Questline, after Malenia is defeated", 'event'),
 r("The Stormhawk King", "Chapel of Anticipation", 'ground_pickup'),
 r("Irina's Letter", "Given after meeting Irina", 'event'),
 r("Chrysalid's Memento", "Stormveil Castle", 'ground_pickup'),
 r("Lord of Blood's Favor", "White Faced Varre Questline, Church of Inhibition or Chapel of Anticipation", 'event'),
 r("Alexander's Innards", "Iron Fist Alexander Questline", 'event'),
 r("Sewing Needle", "Demihuman Chief Duo Drop", 'boss_drop'),
 r("Golden Sewing Needle", "Church of Vows", 'ground_pickup'),
 r("Dectus Medallion Left", "Fort Haight", 'ground_pickup'),
 r("Dectus Medallion Right", "Fort Faroth", 'ground_pickup'),
 r("Rold Medallion", "Given by Melina after Morgott is defeated", 'event'),
 r("Haligtree Secret Medallion Left", "Castle Sol", 'ground_pickup'),
 r("Haligtree Secret Medallion Right", "Given by Albus in the Village of Albinaurics", 'event'),
 r("Rusty Key", "Stormveil Castle", 'ground_pickup'),
 r("Academy Glintstone Key", "Near Glintstone Dragon Smarag", 'ground_pickup'),
 r("Sewer Gaol Key", "Given by Dung Eater after arrival in Leyndell", 'event'),
 r("Drawing Room Key", "Given by Tanith at Volcano Manor", 'event'),
 r("Discarded Palace Key", "Ranni Questline, Baelful Shadow Drop", 'boss_drop'),
 r("Sellian Sealbreaker", "Sellen Questline", 'event'),
 r("Imbued Sword Key", "The Four Belfries", 'ground_pickup'),
 r("Champions Song Painting", "The Shaded Castle", 'ground_pickup'),
 r("Flightless Bird Painting", "Fortified Manor", 'ground_pickup'),
 r("Homing Instinct Painting", "Artist's Shack (Limgrave)", 'ground_pickup'),
 r("Prophecy Painting", "Stormveil Castle", 'ground_pickup'),
 r("Redmane Painting", "Sellia, Town of Sorcery", 'ground_pickup'),
 r("Resurrection Painting", "Artist's Shack (Liurnia of the Lakes)", 'ground_pickup'),
 r("Sorcerer Painting", "Castle Sol", 'ground_pickup'),
 r("Axe Talisman", "Enhances charge attacks.", 'ground_pickup'),
 r("Boltdrake Talisman", "Boosts lightning damage negation.", 'ground_pickup'),
 r("Carian Filigreed Crest", "Lowers FP consumed by skills", 'ground_pickup'),
 r("Cerulean Seed Talisman", "Boosts FP restoration from Flask of Cerulean Tears", 'ground_pickup'),
 r("Claw Talisman", "Enhances jump attacks.", 'ground_pickup'),
 r("Curved Sword Talisman", "Enhances guard counters.", 'ground_pickup'),
 r("Dragoncrest Shield Talisman", "Boosts physical damage negation", 'ground_pickup'),
 r("Flamedrake Talisman", "Boosts fire damage negation.", 'ground_pickup'),
 r("Haligdrake Talisman", "Boosts holy damage negation.", 'ground_pickup'),
 r("Hammer Talisman", "Enhances stamina-reducing attacks against blockers.", 'ground_pickup'),
 r("Lord Of Blood's Exultation", "Enhances critical hits", 'ground_pickup'),
 r("Old Lord's Talisman", "Extends spell effect duration", 'ground_pickup'),
 r("Pearldrake Talisman", "Boosts non-physical damage negation.", 'ground_pickup'),
 r("Primal Glintstone Blade", "Spells consume less FP", 'ground_pickup'),
 r("Radagon Icon", "Shortens spell casting time", 'ground_pickup'),
 r("Spelldrake Talisman", "Boosts magical damage negation.", 'ground_pickup'),
 r("Twinblade Talisman", "Enhances final hit of chain attacks.", 'ground_pickup'),
 r("Lance Talisman", "Enhances attacks on horseback", 'ground_pickup'),
 r("Dragoncrest Greatshield Talisman", "Enormously boosts physical damage negation", 'ground_pickup'),
 r("Warrior Jar Shard", "Boosts the attack power of skills.", 'ground_pickup'),
 r("Greatshield Talisman", "Boosts guarding ability.", 'ground_pickup'),
 r("Millicent's Prosthesis", "Boosts dexterity", 'ground_pickup'),
 r("Spear Talisman", "Enhances counterattacks unique to thrusting weapons", 'ground_pickup'),
 r("Dagger Talisman", "Enhances critical hits.", 'ground_pickup'),
 r("Entwining Umbilical Cord", "Changes demeanour of wearer's actions", 'ground_pickup'),
 r("Bloodboon", "Lord of Blood.", 'ground_pickup'),
 r("Flame", "The most ancient of the Fire Monks' incantations.", 'ground_pickup'),
 r("Lightning Spear", "Godwyn the Golden defeated the ancient dragon Fortissax", 'ground_pickup'),
 r("O", "Incantation of the Fire Monks.", 'ground_pickup'),
 r("Surge", "Superior incantation of the Fire Monks.", 'ground_pickup'),
 r("Triple Rings Of Light", "Radagon.", 'ground_pickup'),
 r("Whirl", "Superior Incantation of the Fire Monks.", 'ground_pickup'),
];
